#spring configuration
spring:
   applicatiion:
      name: mysite
   #devtools - live reload
   devtools:
      livereload:
         enabled: true  
   #mvc
   mvc:
      static-path-pattern: /assets/**
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   web:
      resources:
         static-locations: classpath:/assets/, file:/mysite-uploads/
   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB
   # message resources(internalization, i18n)
   messages:
       always-use-message-format: true
       basename: web/messages_ko
       encoding: utf-8
   aop:
      auto: true
     
# server
server:
   port: 9090